# Generated by Django 6.0 on 2025-12-26 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.TextField()),
                ('value_type', models.CharField(choices=[('string', 'Texte'), ('path', 'Chemin'), ('integer', 'Entier'), ('boolean', 'Booleen'), ('json', 'JSON')], default='string', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parametre',
                'verbose_name_plural': 'Parametres',
                'db_table': 'configuration_settings',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='FileHash',
            fields=[
                ('hash_value', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('filepath', models.CharField(max_length=1000)),
                ('filename', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('category', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hash de fichier',
                'verbose_name_plural': 'Hash de fichiers',
                'db_table': 'file_hashes',
            },
        ),
        migrations.CreateModel(
            name='ProcessingJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_directory', models.CharField(max_length=1000)),
                ('categories', models.JSONField(default=list, help_text='Categories a traiter: Films, Series, Animation, Docs')),
                ('process_all', models.BooleanField(default=False, help_text='Traiter tous les fichiers')),
                ('days_back', models.IntegerField(default=0, help_text='Nombre de jours a remonter (0 = recent)')),
                ('force_mode', models.BooleanField(default=False, help_text='Ignorer verification des hash')),
                ('dry_run', models.BooleanField(default=False, help_text='Mode simulation')),
                ('status', models.CharField(choices=[('queued', "En file d'attente"), ('scanning', 'Analyse en cours'), ('awaiting', 'En attente de confirmation'), ('processing', 'Traitement en cours'), ('completed', 'Termine'), ('failed', 'Echec'), ('cancelled', 'Annule')], default='queued', max_length=20)),
                ('total_files', models.IntegerField(default=0)),
                ('scanned_files', models.IntegerField(default=0)),
                ('processed_files', models.IntegerField(default=0)),
                ('confirmed_files', models.IntegerField(default=0)),
                ('failed_files', models.IntegerField(default=0)),
                ('skipped_files', models.IntegerField(default=0)),
                ('current_file', models.CharField(blank=True, max_length=500)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('launched_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Job de traitement',
                'verbose_name_plural': 'Jobs de traitement',
                'db_table': 'processing_jobs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_path', models.CharField(db_index=True, max_length=1000)),
                ('original_filename', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_hash', models.CharField(blank=True, db_index=True, max_length=64)),
                ('detected_title', models.CharField(blank=True, max_length=500)),
                ('detected_year', models.IntegerField(blank=True, null=True)),
                ('detected_season', models.IntegerField(blank=True, null=True)),
                ('detected_episode', models.IntegerField(blank=True, null=True)),
                ('video_codec', models.CharField(blank=True, max_length=50)),
                ('resolution', models.CharField(blank=True, max_length=20)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('spec_string', models.CharField(blank=True, help_text='Ex: FR x264 1080p', max_length=100)),
                ('tmdb_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('tvdb_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('title_fr', models.CharField(blank=True, max_length=500, verbose_name='Titre francais')),
                ('title_original', models.CharField(blank=True, max_length=500, verbose_name='Titre original')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('overview', models.TextField(blank=True, verbose_name='Synopsis')),
                ('vote_average', models.FloatField(blank=True, null=True, verbose_name='Note')),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('poster_path', models.CharField(blank=True, help_text='TMDB poster path', max_length=200)),
                ('poster_local', models.CharField(blank=True, help_text='Cached local poster path', max_length=500)),
                ('category', models.CharField(choices=[('Films', 'Films'), ('Series', 'Series'), ('Animation', 'Animation'), ('Docs', 'Documentaires'), ('Docs#1', 'Documentaires #1')], db_index=True, max_length=20)),
                ('genre', models.CharField(blank=True, max_length=100)),
                ('genres_list', models.JSONField(default=list)),
                ('directors', models.JSONField(default=list, help_text='Liste des realisateurs')),
                ('cast', models.JSONField(default=list, help_text='Liste des acteurs principaux')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('scanning', 'Analyse'), ('awaiting', 'Confirmation requise'), ('confirmed', 'Confirme'), ('processing', 'En traitement'), ('completed', 'Termine'), ('failed', 'Echec'), ('skipped', 'Ignore')], db_index=True, default='pending', max_length=20)),
                ('formatted_filename', models.CharField(blank=True, max_length=500)),
                ('destination_path', models.CharField(blank=True, max_length=1000)),
                ('symlink_path', models.CharField(blank=True, max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('processing_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='core.processingjob')),
            ],
            options={
                'verbose_name': 'Video',
                'verbose_name_plural': 'Videos',
                'db_table': 'videos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('DEBUG', 'Debug'), ('INFO', 'Info'), ('WARNING', 'Avertissement'), ('ERROR', 'Erreur'), ('SUCCESS', 'Succes')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('details', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.processingjob')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='core.video')),
            ],
            options={
                'verbose_name': 'Log de traitement',
                'verbose_name_plural': 'Logs de traitement',
                'db_table': 'processing_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PendingConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirmation_type', models.CharField(choices=[('title_match', 'Confirmation de titre'), ('genre_select', 'Selection de genre'), ('duplicate', 'Doublon detecte'), ('manual_entry', 'Saisie manuelle requise'), ('not_found', 'Non trouve dans TMDB')], max_length=20)),
                ('tmdb_candidates', models.JSONField(default=list, help_text='Liste des candidats TMDB avec poster, synopsis, etc.')),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('resolution', models.CharField(choices=[('pending', 'En attente'), ('accepted', 'Accepte'), ('rejected', 'Rejete'), ('manual', 'Saisie manuelle'), ('skipped', 'Ignore')], default='pending', max_length=20)),
                ('selected_tmdb_id', models.IntegerField(blank=True, null=True)),
                ('manual_title', models.CharField(blank=True, max_length=500)),
                ('manual_year', models.IntegerField(blank=True, null=True)),
                ('selected_genre', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_confirmations', to='core.processingjob')),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pending_confirmation', to='core.video')),
            ],
            options={
                'verbose_name': 'Confirmation en attente',
                'verbose_name_plural': 'Confirmations en attente',
                'db_table': 'pending_confirmations',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['status', 'category'], name='videos_status_0ab253_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['tmdb_id'], name='videos_tmdb_id_8b4dd4_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['file_hash'], name='videos_file_ha_42b8eb_idx'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['title_fr'], name='videos_title_f_1665f5_idx'),
        ),
        migrations.AddIndex(
            model_name='processinglog',
            index=models.Index(fields=['job', 'level'], name='processing__job_id_b66a7f_idx'),
        ),
        migrations.AddIndex(
            model_name='processinglog',
            index=models.Index(fields=['created_at'], name='processing__created_9b87c6_idx'),
        ),
    ]
